//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLStoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceTbl
    {
        public double Trans { get; set; }
        public string Type { get; set; }
        public string Date { get; set; }
        public double Name { get; set; }
        public string Account { get; set; }
        public string Debit { get; set; }
        public string Credit { get; set; }
    }
}
